name: Sync with Repo 2

on:
  push:
    branches:
      - main # Nhánh cần đồng bộ

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Check out this repository
        uses: actions/checkout@v3

      - name: Debug Remote Repository
        run: |
          echo "Testing remote connection..."
          git remote add sync https://x-access-token:${{ DEPLOY_SECRET }}@github.com/chtruq/capstoneWebsystem.git
          git remote -v  # Hiển thị thông tin remote
          echo "Fetching branches..."
          git fetch sync  # Kiểm tra xem remote có hợp lệ không
          git branch -r  # Hiển thị các nhánh remote (nếu kết nối thành công)

      - name: Sync with Repo 2
        env:
          REPO2_URL: https://x-access-token:${{ DEPLOY_SECRET }}@github.com/chtruq/capstoneWebsystem.git
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "github-action@users.noreply.github.com"
          git remote add sync $REPO2_URL
          git push sync main --force
