# name: Sync with Repo 2

# on:
#   push:
#     branches:
#       - main

# jobs:
#   sync:
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v3
#         with:
#           persist-credentials: false

#       - name: Push to Target Repository
#         env:
#           DEPLOY_SECRET: ${{ secrets.DEPLOY_SECRET }}
#         run: |
#           git config --global user.name "GitHub Action"
#           git config --global user.email "github-action@users.noreply.github.com"

#           # Use https URL with embedded token
#           git remote add sync "https://${DEPLOY_SECRET}@github.com/chtruq/capstoneWebsystem.git"
#           git push sync main --forceaaa

name: Sync to Deployment

on:
  push:
    branches:
      - main
    paths-ignore:
      - ".github/workflows/**"
      - "README.md"
      - ".gitignore"

jobs:
  deploy:
    runs-up: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Sync to Deployment Repository
        env:
          DEPLOY_SECRET: ${{ secrets.DEPLOY_SECRET }}
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "github-action@users.noreply.github.com"
          git remote add deploy "https://${DEPLOY_SECRET}@github.com/chtruq/capstoneWebsystem.git"
          git push deploy main:main --force
